'use strict';
function amountList(totals){const entries=Object.entries(totals);return entries.length?entries.map(([currency,value])=>money(value,currency)).join(' + '):money(0);}
function combinedScenariosPage(){
  const intro=heading('Cenários combinados','Compare planos que reúnem duas ou mais viagens.','<button class="button primary" data-action="new-combined" '+(library.trips.length<2?'disabled':'')+'>+ Novo cenário</button>')+
    '<p class="notice"><strong>Para que serve:</strong> avalie realizar ambas as viagens, realizar apenas uma ou mudar ordem e datas. Exemplo: “Congresso + férias depois”. Custos em moedas diferentes nunca são somados entre si.</p>';
  if(!library.combined_scenarios.length)return intro+'<section class="empty"><h2>Combine seus próximos caminhos</h2><p>Crie um cenário, inclua ao menos duas viagens e ajuste datas ou ordem. Depois você poderá desligar uma delas para comparar a alternativa “apenas uma”.</p></section>';
  return intro+'<div class="cards">'+library.combined_scenarios.map(s=>{const summary=TravelPlanning.scenarioSummary(library,s);return `<article class="record scenario-card"><span class="tag">CENÁRIO COMBINADO</span><h2>${esc(s.nome)}</h2><div class="scenario-items">${s.items.toSorted((a,b)=>(a.order||0)-(b.order||0)).map(item=>{const trip=library.trips.find(t=>t.id===item.trip_id);return `<label class="scenario-item"><input type="checkbox" data-scenario-include="${esc(s.id)}" data-trip-id="${esc(item.trip_id)}" ${item.included!==false?'checked':''}><span><strong>${esc(item.order)}. ${esc(trip.nome)}</strong><small>Dado cadastrado: ${date(trip.data_inicio)} — ${date(trip.data_fim)}</small></span><input aria-label="Início ajustado de ${esc(trip.nome)}" type="date" data-scenario-start="${esc(s.id)}" data-trip-id="${esc(item.trip_id)}" value="${esc(item.data_inicio||trip.data_inicio||'')}"><input aria-label="Fim ajustado de ${esc(trip.nome)}" type="date" data-scenario-end="${esc(s.id)}" data-trip-id="${esc(item.trip_id)}" value="${esc(item.data_fim||trip.data_fim||'')}"></label>`}).join('')}</div><dl class="scenario-facts"><div><dt>Custos cadastrados</dt><dd>${amountList(summary.totals)}</dd></div><div><dt>Dias disponíveis</dt><dd>${summary.availableDays}</dd></div><div><dt>Deslocamentos</dt><dd>${summary.transports}</dd></div><div><dt>Compromissos</dt><dd>${summary.commitments.length}</dd></div></dl><div class="record-actions"><button class="button" data-action="save-combined" data-id="${esc(s.id)}">Salvar ajustes</button><button class="button" data-action="reverse-combined" data-id="${esc(s.id)}">Inverter ordem</button><button class="button danger" data-action="delete-combined" data-id="${esc(s.id)}">Excluir</button></div>${summary.commitments.length?`<p class="muted">Compromissos relevantes: ${summary.commitments.slice(0,4).map(e=>`${esc(e.trip_name)} — ${esc(e.nome)} (${date(e.scenario_date)})`).join('; ')}</p>`:''}</article>`}).join('')+'</div>';
}
function nearbyTripsPage(){
  const findings=TravelPlanning.proximity(library);
  const intro=heading('Viagens próximas','Conflitos calculados e oportunidades entre planejamentos.')+'<p class="notice"><strong>Dado cadastrado</strong> identifica datas e destinos salvos. <strong>Sugestão</strong> é apenas uma possibilidade para você avaliar; uma viagem nunca é tratada como substituta da outra.</p>';
  if(!findings.length)return intro+'<section class="empty"><h2>Nenhuma proximidade encontrada</h2><p>Viagens com datas definidas e até 3 dias livres entre elas aparecerão aqui.</p></section>';
  return intro+'<div class="cards">'+findings.map(f=>`<article class="record ${f.type==='conflict'?'conflict':''}"><span class="tag ${f.type==='conflict'?'danger-tag':''}">${f.type==='conflict'?'CONFLITO':'OPORTUNIDADE'}</span><h2>${esc(f.a.nome)} + ${esc(f.b.nome)}</h2><p><strong>Dado cadastrado:</strong> ${date(f.a.data_inicio)} — ${date(f.a.data_fim)} e ${date(f.b.data_inicio)} — ${date(f.b.data_fim)}.</p>${f.type==='conflict'?`<p>As viagens se sobrepõem por <strong>${f.overlapDays} dia(s)</strong>.</p>`:`<p>Há <strong>${f.gapDays} dia(s) livre(s)</strong> entre as viagens.</p><p class="suggestion"><strong>Sugestão:</strong> ${esc(f.suggestion)}</p>`}</article>`).join('')+'</div>';
}
function globalCalendarPage(){
  const entries=TravelPlanning.calendarEntries(library);
  const intro=heading('Calendário global','Tudo o que tem data, reunido entre todas as viagens.')+'<p class="notice">Inclui viagens, etapas, hospedagens vinculadas a etapas, transportes e eventos. Alertas indicam sobreposição entre viagens ou entre compromissos com horário.</p>';
  if(!entries.length)return intro+'<section class="empty"><h2>Calendário vazio</h2><p>Defina datas nos seus registros para vê-los aqui.</p></section>';
  let month='';return intro+'<div class="calendar-list">'+entries.map(e=>{const next=e.startDate.slice(0,7),header=next!==month?(month=next,`<h2 class="calendar-month">${new Date(next+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2>`):'';return `${header}<article class="calendar-entry ${e.conflicts.length?'conflict':''}"><time datetime="${esc(e.startDate)}">${date(e.startDate)}${e.startTime?' · '+esc(e.startTime):''}</time><div><span class="tag">${esc(e.type)}</span>${e.conflicts.length?'<span class="conflict-label">Conflito de data/horário</span>':''}<h3>${esc(e.label)}</h3><p>${esc(e.trip_name)}${e.endDate!==e.startDate?' · até '+date(e.endDate):''}</p></div><button class="button" data-action="open-calendar-origin" data-trip-id="${esc(e.trip_id)}" data-hash="${esc(e.hash)}">Abrir origem</button></article>`}).join('')+'</div>';
}
document.addEventListener('click',event=>{
  const button=event.target.closest('[data-action]');if(!button)return;
  const action=button.dataset.action,id=button.dataset.id;
  if(action==='new-combined'){
    const name=prompt('Nome do cenário combinado (ex.: Congresso + férias depois):');if(!name?.trim())return;
    const next=structuredClone(library);next.combined_scenarios.push({id:'SC_'+crypto.randomUUID(),nome:name.trim(),items:next.trips.map((trip,index)=>({trip_id:trip.id,included:true,order:index+1,data_inicio:trip.data_inicio||'',data_fim:trip.data_fim||''}))});if(persist(next))render();
  }
  if(action==='save-combined'){
    const next=structuredClone(library),scenario=next.combined_scenarios.find(s=>s.id===id);if(!scenario)return;
    for(const item of scenario.items){const selector=`[data-trip-id="${CSS.escape(item.trip_id)}"]`;item.included=document.querySelector(`[data-scenario-include="${CSS.escape(id)}"]${selector}`).checked;item.data_inicio=document.querySelector(`[data-scenario-start="${CSS.escape(id)}"]${selector}`).value;item.data_fim=document.querySelector(`[data-scenario-end="${CSS.escape(id)}"]${selector}`).value;}
    if(persist(next)){render();toast('Ajustes do cenário salvos.');}
  }
  if(action==='reverse-combined'){const next=structuredClone(library),scenario=next.combined_scenarios.find(s=>s.id===id);scenario.items.reverse().forEach((item,index)=>item.order=index+1);if(persist(next))render();}
  if(action==='delete-combined'&&confirm('Excluir este cenário combinado?')){const next=structuredClone(library);next.combined_scenarios=next.combined_scenarios.filter(s=>s.id!==id);if(persist(next))render();}
  if(action==='open-calendar-origin'&&activateTrip(button.dataset.tripId,false)){location.hash=button.dataset.hash;render();}
});
