const {test}=require('node:test');
const assert=require('node:assert/strict');
require('../core.js');require('../trips.js');require('../comparison.js');
const planning=require('../planning.js');
function fixture(){
  const records=TravelTrips.emptyRecords(),trips=[
    {id:'A',nome:'Viagem A',destino_principal:{cidade:'Recife'},data_inicio:'2027-01-10',data_fim:'2027-01-12'},
    {id:'B',nome:'Viagem B',destino_principal:{cidade:'Natal'},data_inicio:'2027-01-12',data_fim:'2027-01-15'},
    {id:'C',nome:'Viagem C',destino_principal:{cidade:'Fortaleza'},data_inicio:'2027-01-18',data_fim:'2027-01-20'},
  ];
  records.orcamento.push({custo_id:'CA',viagem_id:'A',descricao:'A',valor:100,moeda:'BRL'},{custo_id:'CB',viagem_id:'B',descricao:'B',valor:50,moeda:'USD'});
  records.deslocamentos.push({deslocamento_id:'DA',viagem_id:'A',origem:'Casa',destino:'Recife',data_saida:'2027-01-10',hora_saida:'08:00',data_chegada:'2027-01-10',hora_chegada:'10:00'});
  records.compromissos.push({compromisso_id:'EA',viagem_id:'A',nome:'Evento A',data_inicio:'2027-01-12',hora_inicio:'09:00',data_fim:'2027-01-12',hora_fim:'11:00'},{compromisso_id:'EB',viagem_id:'B',nome:'Evento B',data_inicio:'2027-01-12',hora_inicio:'10:00',data_fim:'2027-01-12',hora_fim:'12:00'});
  return TravelTrips.validate({version:2,trips,active_trip_id:'A',records,combined_scenarios:[]});
}
test('detects overlaps and short consecutive gaps without replacement assumptions',()=>{const result=planning.proximity(fixture());assert.equal(result[0].type,'conflict');assert.equal(result[0].overlapDays,1);const opportunity=result.find(r=>r.a.id==='B'&&r.b.id==='C');assert.equal(opportunity.type,'opportunity');assert.equal(opportunity.gapDays,2);assert.match(opportunity.suggestion,/Avalie ligar/);});
test('combined scenario separates currencies and supports include, order and changed dates',()=>{const scenario={items:[{trip_id:'B',included:false,order:2},{trip_id:'A',included:true,order:1,data_inicio:'2027-02-01',data_fim:'2027-02-03'}]};const result=planning.scenarioSummary(fixture(),scenario);assert.deepEqual(result.totals,{BRL:100});assert.equal(result.availableDays,3);assert.equal(result.transports,1);assert.equal(result.commitments[0].scenario_date,'2027-02-03');scenario.items[0].included=true;assert.deepEqual(planning.scenarioSummary(fixture(),scenario).totals,{BRL:100,USD:50});});
test('global calendar treats events as commitments and only flags real schedule conflicts',()=>{const entries=planning.calendarEntries(fixture()),events=entries.filter(e=>e.type==='Evento'),trips=entries.filter(e=>e.type==='Viagem');assert.equal(events.length,2);assert.deepEqual(events.map(e=>e.conflicts),[['EB'],['EA']]);assert.ok(trips.every(e=>!e.conflicts.includes('EA')&&!e.conflicts.includes('EB')));assert.equal(events[0].hash,'compromissos');assert.equal(events[0].trip_name,'Viagem A');});
test('events on the trip dates but at different hours do not conflict',()=>{const data=fixture();data.records.compromissos.push({compromisso_id:'EC',viagem_id:'A',nome:'Evento C',data_inicio:'2027-01-12',hora_inicio:'13:00',data_fim:'2027-01-12',hora_fim:'14:00'});const events=planning.calendarEntries(data).filter(e=>e.type==='Evento');assert.deepEqual(events.find(e=>e.id==='EC').conflicts,[]);});
test('an event contained in its own trip period does not conflict with that trip',()=>{const data=fixture();data.trips=[{id:'CONGRESSO',nome:'Congresso',data_inicio:'2026-11-01',data_fim:'2026-11-05'}];data.records=TravelTrips.emptyRecords();data.records.compromissos.push({compromisso_id:'ABERTURA',viagem_id:'CONGRESSO',nome:'Abertura',data_inicio:'2026-11-01',hora_inicio:'18:00',data_fim:'2026-11-01',hora_fim:'19:00'});const entries=planning.calendarEntries(data),trip=entries.find(e=>e.id==='CONGRESSO'),event=entries.find(e=>e.id==='ABERTURA');assert.deepEqual(trip.conflicts,[]);assert.deepEqual(event.conflicts,[]);});
test('two events from the same trip only conflict when their times overlap',()=>{const data=fixture();data.trips=[data.trips[0]];data.records=TravelTrips.emptyRecords();data.records.compromissos.push({compromisso_id:'MANHA',viagem_id:'A',nome:'Manhã',data_inicio:'2027-01-10',hora_inicio:'09:00',data_fim:'2027-01-10',hora_fim:'10:00'},{compromisso_id:'TARDE',viagem_id:'A',nome:'Tarde',data_inicio:'2027-01-10',hora_inicio:'14:00',data_fim:'2027-01-10',hora_fim:'15:00'},{compromisso_id:'SOBREPOSTO',viagem_id:'A',nome:'Sobreposto',data_inicio:'2027-01-10',hora_inicio:'09:30',data_fim:'2027-01-10',hora_fim:'10:30'});const byId=Object.fromEntries(planning.calendarEntries(data).map(e=>[e.id,e]));assert.deepEqual(byId.TARDE.conflicts,[]);assert.deepEqual(byId.MANHA.conflicts,['SOBREPOSTO']);assert.deepEqual(byId.SOBREPOSTO.conflicts,['MANHA']);});
test('different trips with overlapping periods conflict with each other',()=>{const entries=planning.calendarEntries(fixture()),a=entries.find(e=>e.type==='Viagem'&&e.id==='A'),b=entries.find(e=>e.type==='Viagem'&&e.id==='B');assert.ok(a.conflicts.includes('B'));assert.ok(b.conflicts.includes('A'));});
test('a trip does not conflict with its own transport or event inside its period',()=>{const data=fixture();data.trips=[data.trips[0]];data.records=TravelTrips.emptyRecords();data.records.deslocamentos.push({deslocamento_id:'TRANSPORTE',viagem_id:'A',origem:'Casa',destino:'Recife',data_saida:'2027-01-10',hora_saida:'08:00',data_chegada:'2027-01-10',hora_chegada:'10:00'});data.records.compromissos.push({compromisso_id:'EVENTO',viagem_id:'A',nome:'Evento',data_inicio:'2027-01-11',hora_inicio:'18:00',data_fim:'2027-01-11',hora_fim:'19:00'});const entries=planning.calendarEntries(data),trip=entries.find(e=>e.type==='Viagem');assert.deepEqual(trip.conflicts,[]);assert.deepEqual(entries.find(e=>e.id==='TRANSPORTE').conflicts,[]);assert.deepEqual(entries.find(e=>e.id==='EVENTO').conflicts,[]);});
test('version 2 migration adds scenarios without losing records and roundtrips them',()=>{const old=fixture();delete old.combined_scenarios;const migrated=TravelTrips.migrate(old);assert.deepEqual(migrated.combined_scenarios,[]);assert.equal(migrated.records.orcamento.length,2);migrated.combined_scenarios.push({id:'S1',nome:'As duas',items:[{trip_id:'A',included:true,order:1},{trip_id:'B',included:true,order:2}]});assert.deepEqual(TravelTrips.migrate(JSON.parse(JSON.stringify(migrated))),migrated);});
