const { test } = require('node:test');
const assert = require('node:assert/strict');
const c = require('../core.js');
function fixture() {
  return {version:1,trip:{id:'test'},records:{estadias:[{estadia_id:'E1',nome:'Congresso',numero_viajantes:1,data_inicio:'2026-11-01',data_fim:'2026-11-05'},{estadia_id:'E2',nome:'Turismo',numero_viajantes:2,data_inicio:'2026-11-05',data_fim:'2026-11-08'}],hoteis:[{hotel_id:'H1',nome:'Hotel A',estadia_id:'E1',preco_diaria:100},{hotel_id:'H2',nome:'Hotel B',estadia_id:'E1',preco_total:600},{hotel_id:'H3',nome:'Hotel C',estadia_id:'E2',preco_total:900,divisao:'IGUAL'}],orcamento:[],roteiro:[]}};
}
test('nights are calendar differences independent of daylight saving',()=>{assert.equal(c.nights({data_inicio:'2026-10-31',data_fim:'2026-11-05'}),5);assert.equal(c.nights({data_inicio:'2026-11-05',data_fim:'2026-11-05'}),null);});
test('quoted total includes all rooms; derived price multiplies rooms and nights',()=>{const s=fixture().records.estadias[0];assert.equal(c.hotelCost({preco_total:500,preco_diaria:100,numero_quartos:2},s).total,500);assert.equal(c.hotelCost({preco_diaria:100,numero_quartos:2},s).total,800);assert.equal(c.hotelCost({preco_diaria:100,numero_noites:2},s).total,200);assert.equal(c.hotelCost({},s).total,null);});
test('choosing a hotel creates exactly one derived expense, without mutating original',()=>{const s=fixture();const next=c.chooseHotel(s,'H1');assert.equal(c.effectiveBudget(next).length,1);assert.equal(c.effectiveBudget(next)[0].valor,400);assert.equal(s.records.hoteis[0].escolhido,undefined);});
test('switching replaces expense only in its stage; deselect removes automatic expense',()=>{let s=c.chooseHotel(fixture(),'H1');s=c.chooseHotel(s,'H3');s=c.chooseHotel(s,'H2');assert.deepEqual(c.effectiveBudget(s).map(r=>r.valor),[600,900]);s=c.chooseHotel(s,'H2');assert.deepEqual(c.effectiveBudget(s).map(r=>r.valor),[900]);});
test('editing stage dates recalculates daily quote but not explicit total',()=>{let s=c.chooseHotel(fixture(),'H1');s.records.estadias[0].data_fim='2026-11-06';assert.equal(c.effectiveBudget(s)[0].valor,500);s=c.chooseHotel(s,'H2');s.records.estadias[0].data_fim='2026-11-07';assert.equal(c.effectiveBudget(s)[0].valor,600);});
test('shared and custom costs are explicit and follow stage traveler counts',()=>{const s=fixture();const stage=s.records.estadias[1];assert.equal(c.personalShare({valor:900,divisao:'IGUAL'},stage),450);assert.equal(c.personalShare({valor:900,divisao:'INDIVIDUAL'},stage),900);assert.equal(c.personalShare({valor:900,divisao:'PERSONALIZADO',minha_parte:300},stage),300);stage.numero_viajantes=3;assert.equal(c.personalShare({valor:1000,divisao:'IGUAL'},stage),333.33);});
test('linked manual paid expense is preserved and suppresses generated duplicate',()=>{let s=c.chooseHotel(fixture(),'H1');s.records.orcamento.push({custo_id:'C1',hotel_id:'H1',valor:400,status:'PAGO'});assert.equal(c.effectiveBudget(s).length,1);assert.equal(c.effectiveBudget(s)[0].status,'PAGO');s=c.chooseHotel(s,'H1');assert.equal(c.effectiveBudget(s).length,1);});
test('incomplete price or missing stage cannot be chosen',()=>{const s=fixture();s.records.hoteis[0].preco_diaria='';assert.throws(()=>c.chooseHotel(s,'H1'));s.records.hoteis[1].estadia_id='unknown';assert.throws(()=>c.chooseHotel(s,'H2'));});
test('paid automatic reservation cannot silently disappear when switching choices',()=>{const s=c.chooseHotel(fixture(),'H1');s.records.hoteis[0].status_custo='PAGO';assert.throws(()=>c.chooseHotel(s,'H2'));assert.throws(()=>c.chooseHotel(s,'H1'));assert.equal(c.effectiveBudget(s)[0].status,'PAGO');});
test('relations reject duplicate choices and invalid traveler/share values',()=>{const s=fixture();s.records.hoteis[0].escolhido=true;s.records.hoteis[1].escolhido='true';assert.throws(()=>c.validateRelations(s));s.records.hoteis[1].escolhido=false;s.records.estadias[0].numero_viajantes=0;assert.throws(()=>c.validateRelations(s));s.records.estadias[0].numero_viajantes=1;s.records.hoteis[0].divisao='PERSONALIZADO';s.records.hoteis[0].minha_parte=1000;assert.throws(()=>c.validateRelations(s));});
test('old backups with no stages or selections retain manual budget',()=>{const s=fixture();s.records.estadias=[];s.records.hoteis=[];s.records.orcamento=[{custo_id:'C1',valor:20,moeda:'BRL'}];assert.equal(c.effectiveBudget(s)[0].valor,20);assert.equal(c.validateRelations(s),s);});
test('transport and food values are automatically included in the complete budget',()=>{const s=fixture();s.records.deslocamentos=[{deslocamento_id:'D1',origem:'Casa',destino:'Praia',preco:'120',moeda:'BRL',status_custo:'PAGO'}];s.records.alimentacao=[{alimentacao_id:'A1',descricao:'Almoço',valor:'45,50',moeda:'BRL',status_custo:'CONFIRMADO'}];const rows=c.effectiveBudget(s);assert.deepEqual(rows.map(r=>r.categoria),['TRANSPORTE','ALIMENTAÇÃO']);assert.deepEqual(c.budget(rows),{BRL:{total:165.5,paid:120}});});
test('linked manual expenses take precedence over automatic transport and food costs',()=>{const s=fixture();s.records.deslocamentos=[{deslocamento_id:'D1',preco:100}];s.records.alimentacao=[{alimentacao_id:'A1',valor:50}];s.records.orcamento=[{custo_id:'C1',deslocamento_id:'D1',valor:90},{custo_id:'C2',alimentacao_id:'A1',valor:40}];assert.deepEqual(c.effectiveBudget(s).map(r=>r.valor),[90,40]);});
test('link suggestions use URL data, reject unsafe protocols, do not invent prices',()=>{const r=c.hotelLink('https://www.booking.com/hotel/br/pousada-do-sol.pt-br.html?checkin=2026-11-01&checkout=2026-11-04');assert.equal(r.nome,'pousada do sol');assert.equal(r.numero_noites,'3');assert.equal(r.fonte,'booking.com');assert.equal(r.preco_total,undefined);assert.throws(()=>c.hotelLink('javascript:alert(1)'));});
test('OCR suggestions require explicitly labeled price and preserve ambiguity',()=>{assert.deepEqual(c.hotelText('Hotel Exemplo\n3 noites\nR$ 250 por noite\nTotal R$ 750,00'),{nome:'Hotel Exemplo',numero_noites:'3',preco_diaria:'250',preco_total:'750'});assert.equal(c.hotelText('R$ 200\nR$ 500').preco_total,undefined);});
test('prints stay in JSON backup but not CSV exchange',()=>{const h={hotel_id:'H1',nome:'Hotel',print_data:'data:image/jpeg;base64,AAAA'};assert.equal(c.parseCSV(c.toCSV([h]))[0].print_data,undefined);assert.equal(JSON.parse(JSON.stringify(h)).print_data,h.print_data);});
